name: carvable
description: A sample dart package from a Dart template.
version: 0.0.1
repository: https://github.com/DrafaKiller/Carvable-dart

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  analyzer: ^5.2.0

dev_dependencies:
  lints: ^2.0.0
