name: carvable
description: Allows you to remove and change parts of something, without modifying the original. Carve objects such as Strings and AstNodes, or implement the generic interface.
version: 0.0.1
repository: https://github.com/DrafaKiller/Carvable-dart
issue_tracker: https://github.com/DrafaKiller/Carvable-dart/issues

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  analyzer: ^5.2.0

dev_dependencies:
  lints: ^2.0.0
